// This file is generated by build-vercel.js
// Placeholder - will be overwritten during build
export default async function handler(req, res) {
  return res.status(500).json({ message: "Build not completed" });
}

